name: kyouth-chat-app

services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    networks:
      - chat-app
    depends_on:
      - backend
    environment:
      - BACKEND_URL=${BACKEND_URL}
  backend:
    build: ./backend
    networks:
      - chat-app
    environment:
      - API_KEY=${API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}

networks:
  chat-app: